// Restrições de Unicidade
CREATE CONSTRAINT UNIQUE_PROJECT_KEY IF NOT EXISTS
FOR (p:Project) REQUIRE p.key IS UNIQUE;

CREATE CONSTRAINT UNIQUE_FILE_PATH IF NOT EXISTS
FOR (f:File) REQUIRE f.path IS UNIQUE;

// Índices de busca rápida
CREATE INDEX INDEX_CLASS_NAME IF NOT EXISTS
FOR (c:Class) ON (c.name);
